---
title: "5291_project"
author: "Yichen Yuan"
date: "9/25/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r construct training data}
install.packages('devtools')
library(devtools)

devtools::install_github("abresler/nbastatR")
library(nbastatR)
library(plyr)

#all players played 2017-18;active players
players_2018 <- seasons_players(seasons = 2018,nest_data = F,return_message = T)
players_2018_active <- players_2018[players_2018$isActive==TRUE, ]

#schedule 18-19
schedule_19_raw <- current_schedule()
schedule_19_regular <- schedule_19_raw[-(1:79),]
schedule_19 <- cbind(as.character(schedule_19_regular$dateGame),schedule_19_regular$slugTeamAway,schedule_19_regular$slugTeamHome)
colnames(schedule_19) <- c("date", "teamaway","teamhome")

#schedule 17-18: 1230 games
schedule_18 <- seasons_schedule(seasons = 2018)

#gamelog 17-18:1230 games and 540 players
gamelog_2018_full <- game_logs(seasons = 2018, league = "NBA",result_types = "player", season_types = "Regular Season",nest_data = F, assign_to_environment = TRUE, return_message = TRUE)
#write.csv(gamelog_2018_full,'gamelog_2018_full.csv')

# get players played over 60 games in 2017-18 season
each_player_2018 <- unique(gamelog_2018_full$idPlayer)
count <- count(gamelog_2018_full$idPlayer)
id_train <- count[count$freq >= 60,]$x

player_bref_2018 <- bref_players_stats(seasons = 2018, tables = c("per_game"),only_totals = F)
#write.csv(player_bref_2018,"player_bref_2018.csv")
player_bref_2017 <- bref_players_stats(seasons = 2017, tables = c("per_game"),only_totals = F)
player_bref_2016 <- bref_players_stats(seasons = 2016, tables = c("per_game"),only_totals = F)
player_bref_15_17 <- bref_players_stats(seasons = 2015:2017, tables = c("per_game"),only_totals = F)
#write.csv(player_bref_15_17,"player_bref_15_17.csv")

game_log_train <- c()
for (i in 1:length(id_train)){
  add <- subset(gamelog_2018_full, idPlayer == id_train[i])
  game_log_train <- rbind(game_log_train,add)
}
game_log_train_beta <-  data.frame(game_log_train$namePlayer, game_log_train$idPlayer,
                          game_log_train$dateGame,game_log_train$idGame, game_log_train$slugTeam,
                          game_log_train$locationGame, game_log_train$slugOpponent,
                          game_log_train$outcomeGame,
                          game_log_train$pts,game_log_train$fg3m,game_log_train$treb,game_log_train$ast,game_log_train$stl,game_log_train$blk,
                          game_log_train$tov)
colnames(game_log_train_beta)<- c("namePlayer","idPlayer","dateGame","idGame","Team","home_Away","Opponent","outcome","pts","3pm","reb","ast","stl","blk","tov")

# add position
game_log_train_final$position <- player_bref_2018$idPosition[match(game_log_train_beta$idPlayer,player_bref_2018$idPlayerNBA)]

#???????? add double double

#???????? add triple double

# Game Lag variables
game_log_train_final = list()
unique_teams = unique(game_log_train_beta$Team)
lag_var = c("pts","3pm","reb","ast","stl","blk","tov")

for (i in 1:length(unique_teams)) {
  team_df = game_log_train_beta[game_log_train_beta$Team == unique_teams[i], ]
      for (j in 1:3) {
            for (v in lag_var) {
                  team_df = slide(team_df, Var = v, slideBy = -j)
            }
      }
      game_log_train_final[[i]] = team_df
}

game_log_train_final = data.frame(do.call(rbind, game_log_train_final))

all_teams_df = data.frame(do.call(rbind, all_teams_df))


#???????????plan is to write a function to make season lag easily
# add pts season lag
game_log_train_final$pts_season_lag1 <- player_bref_2017$ptsPerGame[match(game_log_train_final$idPlayer,player_bref_2017$idPlayerNBA)]

game_log_train_final$pts_season_lag2 <- player_bref_2016$ptsPerGame[match(game_log_train_final$idPlayer,player_bref_2016$idPlayerNBA)]

game_log_train_final$pts_season_lag3 <- player_bref_2015$ptsPerGame[match(game_log_train_final$idPlayer,player_bref_2015$idPlayerNBA)]

# add 3pm season lag
game_log_train_final[,'3pm_season_lag1'] <- player_bref_2017$fg3mPerGame[match(game_log_train_final$idPlayer,player_bref_2017$idPlayerNBA)]

game_log_train_final[,'3pm_season_lag2'] <- player_bref_2016$fg3mPerGame[match(game_log_train_final$idPlayer,player_bref_2016$idPlayerNBA)]

game_log_train_final[,'3pm_season_lag3'] <- player_bref_2015$fg3mPerGame[match(game_log_train_final$idPlayer,player_bref_2015$idPlayerNBA)]

# add reb season lag

# add ast season lag 

# add stl season lag

# add blk season lag

# add tov season lag

# add double double season lag

# add Triple double season lag

```


```{r construct pre-game data for prediction}

```


```{r model fitting to get predicted fantasy score}

```


```{r combine name pos fs and salary}

```


```{r form team}

```